import { ArrowRight, Braces, Check, EyeOff, Fingerprint, Info, LoaderCircle, Play, RotateCcw, ShieldCheck } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useListSources, usePreviewMasking } from '@workspace/api-client-react';
import type { MaskingPreview } from '@workspace/api-client-react';
import { PageHeading } from '@/components/app-shell';

const fieldOptions = ['email', 'phone', 'national_id', 'address', 'credit_card'];
const labels: Record<string, string> = { email: 'email', phone: 'phone', national_id: 'national_id', address: 'address', credit_card: 'credit_card' };

export default function MaskingPage() {
  const sourcesQuery = useListSources();
  const previewMutation = usePreviewMasking();
  const [sourceId, setSourceId] = useState('');
  const [fields, setFields] = useState(['email', 'phone', 'national_id']);
  const [preview, setPreview] = useState<MaskingPreview | null>(null);
  useEffect(() => { if (!sourceId && sourcesQuery.data?.[0]) setSourceId(sourcesQuery.data[0].id); }, [sourceId, sourcesQuery.data]);
  const toggleField = (field: string) => setFields((current) => current.includes(field) ? current.filter((item) => item !== field) : [...current, field]);
  const runPreview = () => { if (!sourceId || fields.length === 0) return; previewMutation.mutate({ data: { sourceId, fields } }, { onSuccess: (result) => setPreview(result) }); };
  return <section className="page-in mx-auto max-w-[1440px] px-5 py-8 md:px-9 md:py-10">
    <PageHeading eyebrow="Entorno de prueba" title="Previsualización de anonimización" description="Comprueba cómo se verán los datos protegidos antes de moverlos a un entorno de test." action={<div className="flex items-center gap-2 text-xs text-muted-foreground"><ShieldCheck size={16} className="text-primary" /> Nunca modifica producción</div>} />
    <div className="grid gap-6 xl:grid-cols-[310px_1fr]">
      <div className="h-fit rounded-2xl border border-card-border bg-card p-5 shadow-[var(--shadow-card)]"><div className="flex items-center gap-2"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#e4f2ef] text-[#237b6c]"><Fingerprint size={18} /></div><div><p className="font-display text-sm font-bold">Configura una vista</p><p className="text-[11px] text-muted-foreground">Selecciona qué proteger</p></div></div><label className="mt-7 block label-caps">Fuente de datos</label><select value={sourceId} onChange={(event) => { setSourceId(event.target.value); setPreview(null); }} disabled={sourcesQuery.isLoading} className="mt-2 h-11 w-full rounded-lg border border-border bg-background px-3 text-xs font-semibold outline-none focus:border-primary" data-testid="select-masking-source"><option value="">Selecciona una fuente</option>{(sourcesQuery.data ?? []).map((source) => <option value={source.id} key={source.id}>{source.name}</option>)}</select><label className="mt-6 block label-caps">Campos a anonimizar</label><div className="mt-3 space-y-2">{fieldOptions.map((field) => <button key={field} onClick={() => toggleField(field)} className={`flex w-full items-center gap-3 rounded-lg border px-3 py-2.5 text-left transition-colors ${fields.includes(field) ? 'border-primary/40 bg-[#edf8f4] text-[#256f65]' : 'border-border bg-background text-muted-foreground hover:border-primary/30'}`} data-testid={`button-toggle-field-${field}`}><span className={`grid h-4 w-4 place-items-center rounded border ${fields.includes(field) ? 'border-primary bg-primary text-white' : 'border-border'}`}>{fields.includes(field) && <Check size={11} />}</span><span className="font-mono text-[11px]">{labels[field]}</span></button>)}</div><div className="mt-6 rounded-xl bg-[#f7f3e9] p-3.5 text-xs leading-5 text-[#7c6844]"><Info size={14} className="mb-1.5 text-[#a17c35]" /><span>Los valores se sustituyen con tokens consistentes, preservando el formato útil para QA.</span></div><button disabled={!sourceId || fields.length === 0 || previewMutation.isPending} onClick={runPreview} className="mt-6 flex h-11 w-full items-center justify-center gap-2 rounded-lg bg-[#173d45] text-xs font-bold text-white transition-transform hover:-translate-y-0.5 disabled:cursor-not-allowed disabled:opacity-60" data-testid="button-run-masking-preview">{previewMutation.isPending ? <LoaderCircle size={15} className="animate-spin" /> : <Play size={14} />} Generar preview <ArrowRight size={14} /></button></div>
      <div className="min-h-[520px] rounded-2xl border border-card-border bg-card shadow-[var(--shadow-card)]"><div className="flex flex-col gap-3 border-b border-border p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="label-caps">Resultado seguro</p><h2 className="mt-1 font-display text-lg font-bold tracking-[-0.03em]">{preview ? `${preview.records.toLocaleString('es-ES')} registros preparados` : 'Tu previsualización aparecerá aquí'}</h2></div>{preview && <button onClick={() => setPreview(null)} className="inline-flex items-center gap-1.5 self-start text-xs font-bold text-muted-foreground hover:text-foreground" data-testid="button-reset-masking-preview"><RotateCcw size={13} /> Limpiar</button>}</div>{previewMutation.isError ? <div className="flex h-[410px] items-center justify-center p-8 text-center"><div><EyeOff className="mx-auto mb-3 text-[#bf5a4e]" size={28} /><p className="font-display font-bold">No pudimos generar la preview</p><p className="mt-1 text-sm text-muted-foreground">Revisa la fuente y vuelve a intentarlo.</p></div></div> : preview ? <div className="overflow-x-auto p-5"><div className="mb-4 flex items-center gap-2 text-xs text-primary"><span className="h-2 w-2 rounded-full bg-primary" /> Campos anonimizados: {preview.maskedFields.join(', ')}</div><table className="w-full min-w-[560px] border-separate border-spacing-0 overflow-hidden rounded-xl border border-border text-left"><thead><tr className="bg-[#f5f8f8]">{Object.keys(preview.rows[0] ?? {}).map((key) => <th className="border-b border-border px-4 py-3 font-mono text-[10px] uppercase tracking-[0.1em] text-muted-foreground" key={key}>{key}</th>)}</tr></thead><tbody>{preview.rows.map((row, index) => <tr className="group" key={index}>{Object.entries(row).map(([key, value]) => <td className={`border-b border-border/70 px-4 py-3 font-mono text-xs last:border-0 ${preview.maskedFields.includes(key) ? 'text-[#247c6c]' : 'text-muted-foreground'}`} key={key}>{preview.maskedFields.includes(key) && <span className="mr-1.5 inline-block h-1.5 w-1.5 rounded-full bg-[#5db69f] align-middle" />}{value}</td>)}</tr>)}</tbody></table></div> : <div className="flex h-[410px] items-center justify-center p-8 text-center"><div className="max-w-sm"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-[#edf8f4] text-[#237b6c]"><Braces size={25} /></div><p className="mt-5 font-display text-lg font-bold">Datos reales, riesgo cero</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Elige una fuente y los campos sensibles. Verás una muestra enmascarada lista para validar tus pruebas.</p></div></div>}</div>
    </div>
  </section>;
}